### ISSUE TITLE
Surface config extensions package in Options topic

### ISSUE THREAD

**Issue by Phrohdoh** [aspnet/Docs#7743]
The following sample code does not compile on `2.1.300`:

```csharp
IServiceCollection services = new ServiceCollection();
IConfiguration config = new ConfigurationBuilder().Build();
services.Configure<MyOptions>("named_options_1", config);
```

The following error is given:

```
error CS1503: Argument 3: cannot convert from 'Microsoft.Extensions.Configuration.IConfiguration' to 'System.Action<MyOptions>'
```

The only available `Configure` extension methods have the following signatures:

```csharp
public static IServiceCollection Configure<TOptions>(this IServiceCollection services, string name, Action<TOptions> configureOptions) where TOptions : class;
public static IServiceCollection Configure<TOptions>(this IServiceCollection services, Action<TOptions> configureOptions) where TOptions : class;
```

Neither of which, as you can see, take an `IConfiguration` as a parameter which is what the [documentation](https://github.com/aspnet/Docs/blob/a9bbe631355235df6c773d5b1ad08dc05f8ed62b/aspnetcore/fundamentals/configuration/options/sample/Startup.cs#L64) tells readers to provide.

---

Note that samples 1, 3, and 6 do not use the signatures reproduced above so I assume they are all invalid.

---

This is quite frustrating as a user who is now spending time on wiring up configuration instead of writing and validating business logic.

---

Is there a specific NuGet package that will provide the exact signatures used in the samples that is not one of the following (locally all of these are version `2.1.1`)?

```
Microsoft.Extensions.Configuration
Microsoft.Extensions.Configuration.EnvironmentVariables
Microsoft.Extensions.Configuration.Json
Microsoft.Extensions.DependencyInjection
Microsoft.Extensions.Options
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Phrohdoh ... https://docs.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.optionsconfigurationservicecollectionextensions.configure

Since you got stuck here, I'm sure others will come to the same end. I'll work on an enhancement to surface this. Let's use this issue to track the work.

btw--- Does your app reference the `Microsoft.AspNetCore.App` package, or does your app list packages explicitly in the project file? That extensions package is probably a transitive reference, and your app probably isn't getting it. Namespaces in `using` statements don't seem to be the problem here, so that's why I'm guessing this is a package reference problem.

**Comment by guardrex** [comment]
Yeah ... check the deps here: https://www.nuget.org/packages/Microsoft.AspNetCore.App/

That one ... *Microsoft.Extensions.Options.ConfigurationExtensions* ... is in the `App` package.

**Comment by Phrohdoh** [comment]
Thanks a ton for your time and investigative work, @guardrex. I truly appreciate it!

After adding the `Microsoft.Extensions.Options.ConfigurationExtensions` package explicitly (as I'm writing a console app so not using aspnetcore) I am back on track and solving different issues. :)

**Comment by guardrex** [comment]
Sure thing. I'm sure in spots that we're relying too heavily on devs using the `App` package. It's the recommended approach, but it's fair to say that docs should support both approaches. In many spots, we have it covered well. I'm opting for language that goes along the lines of 'this scenario requires the X package, which is included in the `App` package.' I'll keep pushing these topics in that direction, and I'll get that language into the Options topic. Thanks again for opening this issue to let me know.

**Comment by guardrex** [comment]
There's no master list/tracking issue for this type of update. It's somewhat ad hoc. Each topic will be addressed as an author or community member performs other updates. I'm looking and revising along with our extensive 2.1 sample updates on #5495, which are turning out to be major topic overhauls in many cases. I'll try to catch/update the language around packages as I go.
